# -*- coding: utf-8 -*-
"""Lab_6_Babkers_algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5Qyb7KQLm9FGTpIs3U92KPZ27GZakhG
"""

class BankersResource:
    def __init__(self):
        self.total_resources = 0
        self.available = 0
        self.jobs = [] # List of dictionaries containing job data
        self.initialized = False

    def init_system(self):
        print("\n--- 1. Initialize System ---")
        self.total_resources = int(input("Enter total number of resources in the system: "))
        num_jobs = int(input("Enter total number of jobs: "))

        self.jobs = []
        total_allocated = 0

        for i in range(num_jobs):
            print(f"\nFor Job {i+1}:")
            max_need = int(input("  Maximum resources required: "))
            allocated = int(input("  Resources currently allocated: "))

            # Calculate remaining need
            remaining = max_need - allocated
            total_allocated += allocated

            self.jobs.append({
                'id': i+1,
                'max': max_need,
                'alloc': allocated,
                'rem': remaining
            })

        self.available = self.total_resources - total_allocated
        self.initialized = True

        print("\nInitialization complete.")
        # Run an initial safety check
        safe, seq = self.is_safe()
        if safe:
            print(f"Initial state is SAFE. Safe sequence: {seq}")
        else:
            print("WARNING: Initial state is UNSAFE (Deadlock inevitable).")

    def check_execution_status(self):
        """Logic to determine if jobs must wait or can execute based on current available."""
        print("\n--- Execution Status Analysis ---")
        for job in self.jobs:
            if job['rem'] <= self.available:
                print(f"Job {job['id']}: CAN BE EXECUTED (Need {job['rem']} <= Avail {self.available})")
            else:
                print(f"Job {job['id']}: MUST WAIT (Need {job['rem']} > Avail {self.available})")

    def print_table(self):
        if not self.initialized:
            print("\nPlease initialize the system first (Option 1).")
            return

        print("\n--- Current System State ---")
        print(f"Total Resources in System: {self.total_resources}")
        print(f"Currently Available: {self.available}\n")

        print("\n" + "="*60)
        print(f"{'Job ID':<8} | {'Allocated':<10} | {'Max Need':<10} | {'Remaining':<10} | {'Status':<10}")
        print("-" * 60)
        for job in self.jobs:
            status = "CAN RUN" if job['rem'] <= self.available else "MUST WAIT"
            print(f"{job['id']:<8} | {job['alloc']:<10} | {job['max']:<10} | {job['rem']:<10} | {status:<10}")
        print("-" * 60)
        print(f"System Available Resources: {self.available}")
        print("="*60)

    def is_safe(self):
        """Core algorithm to determine if the current state is safe."""
        work = self.available
        finish = [False] * len(self.jobs)
        safe_sequence = []

        # We need to find a sequence where all jobs can finish
        while len(safe_sequence) < len(self.jobs):
            found_runnable_job = False

            for i, job in enumerate(self.jobs):
                # If job isn't finished AND its remaining needs can be met by available 'work'
                if not finish[i] and job['rem'] <= work:
                    # Simulate the job finishing and returning its allocated resources
                    work += job['alloc']
                    finish[i] = True
                    safe_sequence.append(job['id'])
                    found_runnable_job = True

            # If we looped through all jobs and couldn't find one that can run, it's unsafe
            if not found_runnable_job:
                return False, []

        # If we successfully finished all jobs, it's safe
        return True, safe_sequence

    def make_request(self):
        if not self.initialized:
            print("\nPlease initialize the system first (Option 1).")
            return

        print("\n--- 2. Make Request ---")
        job_id = int(input(f"Enter Job ID making the request (1 to {len(self.jobs)}): "))

        if job_id < 1 or job_id > len(self.jobs):
            print("Invalid Job ID.")
            return

        request = int(input(f"Enter number of resources requested by Job {job_id}: "))
        job = self.jobs[job_id-1]

        # Check 1: Is the request valid (not asking for more than declared max)?
        if request > job['rem']:
            print(f"Error: Job has exceeded its maximum claim. It only needs {job['rem']} more.")
            return

        # Check 2: Are there enough resources available right now?
        if request > self.available:
            print("Error: Resources are not available right now. Process must wait.")
            return

        # Temporary allocation
        self.available -= request
        job['alloc'] += request
        job['rem'] -= request

        # Check 3: Is the resulting state safe?
        is_safe_state, seq = self.is_safe()

        if is_safe_state:
            print(f"Request GRANTED. The system remains in a safe state.")
            print(f"New safe sequence: {seq}")
        else:
            print("Request DENIED. Granting this would lead to an UNSAFE state (potential deadlock).")
            # Rollback the allocation
            self.available += request
            job['alloc'] -= request
            job['rem'] += request

def main():
    banker = BankersResource()

    while True:
        print("\n" + "="*30)
        print("Banker's Algorithm Simulator")
        print("="*30)
        print("1 - Declare all jobs (Init)")
        print("2 - Make a request")
        print("3 - Print current table")
        print("4 - Exit")

        choice = input("Select an option (1-4): ")

        if choice == '1':
            banker.init_system()
        elif choice == '2':
            banker.make_request()
        elif choice == '3':
            banker.print_table()
        elif choice == '4':
            print("Exiting...")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()

